### ISSUE TITLE
Atlas Fails If Entry Point Isn't src

### ISSUE THREAD

**Issue by dyoder** [dashkite/atlas#24]
If the `genie.yaml` config has an entry point like this:

```yaml
atlas:
  target: ./build/browser/lookbook/index.html
  entries:
    - ./build/browser/lookbook/index.js
```

we get an error from Atlas:

```
Cannot read properties of undefined (reading 'scope')
```

which is due to trying to dereference `import` [here](https://github.com/dashkite/atlas/blob/541db7a06768e941c55416fa54ab9cff0dc1b0b2/src/generators/index.coffee#L25).
